/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./index.tsx",
    "./App.tsx",
    "./types.ts",
    "./constants.tsx",
    "./components/**/*.{js,ts,jsx,tsx}",
    "./hooks/**/*.{js,ts,jsx,tsx}",
    "./platform/**/*.{js,ts,jsx,tsx}",
    "./storage/**/*.{js,ts,jsx,tsx}",
    "./leaderboard/**/*.{js,ts,jsx,tsx}",
    "./src/**/*.{html,css}",
  ],
  theme: {
    extend: {
      screens: {
        'xs': '375px',
        'sm': '414px',
        'md': '428px',
      },
      spacing: {
        'safe-top': 'env(safe-area-inset-top, 0px)',
        'safe-bottom': 'env(safe-area-inset-bottom, 0px)',
        'safe-left': 'env(safe-area-inset-left, 0px)',
        'safe-right': 'env(safe-area-inset-right, 0px)',
      },
      maxWidth: {
        'mobile': '428px',
      },
      animation: {
        'fade-in-up': 'fadeInUp 300ms ease-out',
        'shake': 'shake 0.5s infinite',
        'curtain-drop': 'curtainDrop 0.5s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'scale-up': 'scaleUp 0.6s cubic-bezier(0.34, 1.56, 0.64, 1) 0.2s forwards',
        'sunset': 'sunsetGlow 3s ease infinite',
        // P1: New animation classes
        'page-enter': 'pageEnter 0.35s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'page-exit': 'pageExit 0.2s ease-in forwards',
        'event-result-transition': 'eventResultGlow 0.5s ease-out',
        'float-gain': 'floatGain 1.2s ease-out forwards',
        'float-loss': 'floatLoss 1.2s ease-in forwards',
        'stat-pulse-up': 'statPulseUp 0.6s ease-out',
        'stat-pulse-down': 'statPulseDown 0.6s ease-out',
        'risk-breathing': 'riskBreathing 1.5s ease-in-out infinite',
        'screen-shake': 'screenShake 0.6s cubic-bezier(0.36, 0.07, 0.19, 0.97) both',
        'crisis-flash': 'crisisFlash 0.8s ease-out',
        'fortune-glow': 'fortuneGlow 1s ease-out',
        'death-transition': 'deathDesaturate 1.5s ease-in-out forwards',
        'victory-transition': 'victoryGlow 1.5s ease-out forwards',
        'metro-ending': 'metroReveal 2s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'buff-glow': 'buffGlow 2s ease-in-out infinite',
        'debuff-flash': 'debuffFlash 1.5s ease-in-out infinite',
      },
      keyframes: {
        fadeInUp: {
          '0%': { opacity: '0', transform: 'translateY(10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        shake: {
          '0%': { transform: 'translate(1px, 1px) rotate(0deg)' },
          '10%': { transform: 'translate(-1px, -2px) rotate(-0.5deg)' },
          '20%': { transform: 'translate(-2px, 0px) rotate(0.5deg)' },
          '30%': { transform: 'translate(2px, 2px) rotate(0deg)' },
          '40%': { transform: 'translate(1px, -1px) rotate(0.5deg)' },
          '50%': { transform: 'translate(-1px, 2px) rotate(-0.5deg)' },
          '60%': { transform: 'translate(-2px, 1px) rotate(0deg)' },
          '70%': { transform: 'translate(2px, 1px) rotate(-0.5deg)' },
          '80%': { transform: 'translate(-1px, -1px) rotate(0.5deg)' },
          '90%': { transform: 'translate(1px, 2px) rotate(0deg)' },
          '100%': { transform: 'translate(1px, -2px) rotate(-0.5deg)' },
        },
        curtainDrop: {
          '0%': { transform: 'translateY(-100%)' },
          '100%': { transform: 'translateY(0)' },
        },
        scaleUp: {
          '0%': { transform: 'scale(0.5)', opacity: '0' },
          '50%': { transform: 'scale(1.1)', opacity: '1' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        sunsetGlow: {
          '0%': { backgroundPosition: '0% 50%' },
          '50%': { backgroundPosition: '100% 50%' },
          '100%': { backgroundPosition: '0% 50%' },
        },
        // P1: New keyframes
        pageEnter: {
          '0%': { opacity: '0', transform: 'translateY(16px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        pageExit: {
          '0%': { opacity: '1', transform: 'translateY(0)' },
          '100%': { opacity: '0', transform: 'translateY(12px)' },
        },
        eventResultGlow: {
          '0%': { filter: 'brightness(1.2) blur(2px)' },
          '100%': { filter: 'brightness(1) blur(0)' },
        },
        floatGain: {
          '0%': { opacity: '1', transform: 'translateY(0) scale(1)' },
          '30%': { opacity: '1', transform: 'translateY(-20px) scale(1.2)' },
          '100%': { opacity: '0', transform: 'translateY(-60px) scale(0.8)' },
        },
        floatLoss: {
          '0%': { opacity: '1', transform: 'translateY(0) scale(1)' },
          '30%': { opacity: '1', transform: 'translateY(10px) scale(1.1)' },
          '100%': { opacity: '0', transform: 'translateY(40px) scale(0.8)' },
        },
        statPulseUp: {
          '0%': { transform: 'scale(1)', filter: 'brightness(1)' },
          '30%': { transform: 'scale(1.15)', filter: 'brightness(1.3)' },
          '100%': { transform: 'scale(1)', filter: 'brightness(1)' },
        },
        statPulseDown: {
          '0%': { transform: 'scale(1)', filter: 'brightness(1)' },
          '30%': { transform: 'scale(1.15)', filter: 'brightness(1.3)' },
          '100%': { transform: 'scale(1)', filter: 'brightness(1)' },
        },
        riskBreathing: {
          '0%, 100%': { boxShadow: '0 0 4px rgba(245, 74, 69, 0.3)' },
          '50%': { boxShadow: '0 0 12px rgba(245, 74, 69, 0.7)' },
        },
        screenShake: {
          '0%, 100%': { transform: 'translate(0, 0) rotate(0deg)' },
          '10%': { transform: 'translate(-4px, -2px) rotate(-0.5deg)' },
          '20%': { transform: 'translate(3px, 3px) rotate(0.5deg)' },
          '30%': { transform: 'translate(-3px, -1px) rotate(-0.3deg)' },
          '40%': { transform: 'translate(2px, -2px) rotate(0.3deg)' },
          '50%': { transform: 'translate(-2px, 1px) rotate(-0.2deg)' },
          '60%': { transform: 'translate(1px, -1px) rotate(0.2deg)' },
          '70%': { transform: 'translate(-1px, 2px) rotate(-0.1deg)' },
          '80%': { transform: 'translate(1px, -1px) rotate(0.1deg)' },
          '90%': { transform: 'translate(-1px, 1px) rotate(0deg)' },
        },
        crisisFlash: {
          '0%': { opacity: '0' },
          '15%': { opacity: '1' },
          '30%': { opacity: '0.3' },
          '45%': { opacity: '1' },
          '60%': { opacity: '0.5' },
          '100%': { opacity: '0' },
        },
        fortuneGlow: {
          '0%': { boxShadow: '0 0 0 rgba(234, 179, 8, 0)' },
          '30%': { boxShadow: '0 0 40px rgba(234, 179, 8, 0.4), inset 0 0 20px rgba(234, 179, 8, 0.1)' },
          '100%': { boxShadow: '0 0 0 rgba(234, 179, 8, 0)' },
        },
        deathDesaturate: {
          '0%': { filter: 'grayscale(0) brightness(1)' },
          '100%': { filter: 'grayscale(1) brightness(0.7)' },
        },
        victoryGlow: {
          '0%': { transform: 'scale(1)', filter: 'brightness(1)' },
          '50%': { transform: 'scale(1.02)', filter: 'brightness(1.3) saturate(1.3)' },
          '100%': { transform: 'scale(1)', filter: 'brightness(1.1) saturate(1.1)' },
        },
        metroReveal: {
          '0%': { opacity: '0', transform: 'scale(0.8)', filter: 'blur(8px)' },
          '100%': { opacity: '1', transform: 'scale(1)', filter: 'blur(0)' },
        },
        buffGlow: {
          '0%, 100%': { boxShadow: '0 0 2px rgba(0, 185, 107, 0.3)' },
          '50%': { boxShadow: '0 0 8px rgba(0, 185, 107, 0.6)' },
        },
        debuffFlash: {
          '0%, 100%': { boxShadow: '0 0 2px rgba(245, 74, 69, 0.3)' },
          '50%': { boxShadow: '0 0 8px rgba(245, 74, 69, 0.6)' },
        },
      },
    },
  },
  plugins: [],
}
